server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

app:
  auth:
    client:
      id: oidc-client
      secret: secret
      redirect-uri: "http://localhost:3000/api/auth/callback/spring"
      logout-redirect-uri: "http://localhost:3000/"